name: Java CI

on:
  push:
    branches:
      - master
      - stage

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: nanasess/setup-chromedriver@master
        with:
          chromedriver-version: '80.0.3987.106'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Download Selenium
        run: curl -O http://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar

      - name: Start Selenium
        run: java -jar selenium-server-standalone-3.141.59.jar -log selenium.log &

      - name: Build with Maven
        run: mvn -Dbrowser=headless install -Dcucumber.options="--tags @BVT"
        #run: mvn -Dbrowser=headless clean test -Pfull